### DISCUSSION TITLE
How to decode missing key as Option

### DISCUSSION THREAD

**Discussion by exoego** [VirtusLab/scala-yaml#150] [Q&A]
Given
```yaml
user1:
  name: John
  # user-type is missing
user2:
  name: Jane
  user-type: Admin
```

```scala
case class User(name: String, `user-type`: String) derives YamlDecoder

val decoded = yaml.as[Map[String, User]]
```
results in `Left(ConstructError(Key user-type doesn't exist in parsed document))`

I would like to decode missing key as Option.
