### DISCUSSION TITLE
Feature request: anchors & aliases

### DISCUSSION THREAD

**Discussion by kpodsiad** [VirtusLab/scala-yaml#36] [Ideas]
YAML anchors are a feature which let you identify an item and then reference it elsewhere in your file.
```yaml
services:
  first:
    image: my-image:latest
    environment: &env
      - CONFIG_KEY
      - EXAMPLE_KEY
      - DEMO_VAR
  second:
    image: another-image:latest
    environment: *env
```
